export const META_ANALYSIS_DEFAULTS = {
  outcome_subcategory_behavior: [
    "meat consumption",
    "vegetarian consumption",
    "vegan consumption",
  ],
  outcome_subcategory_intention: [
    "meat consumption intentions",
    "vegetarian consumption intentions",
    "vegan consumption intentions",
  ],
  outcome_subcategory_attitude: [],
  outcome_measurement_type: [
    "survey",
    "meal choice",
    "sales data",
    "food diary",
  ],
  intervention_content: [
    "animal welfare",
    "health",
    "environment",
    "personal image",
    "taste/disgust",
    "none",
  ],
  intervention_mechanism: [
    "factual",
    "choice architecture",
    "identity",
    "logical argument",
    "price",
    "other",
    "negative emotional",
    "perspective taking",
    "goal pursuit",
    "norms",
    "origin of animal product",
    "infotainment",
    "celebrity",
    "symbolic meaning",
    "positive emotional",
    "taste",
  ],
  intervention_medium: [
    "text",
    "presentation",
    "video",
    "3D video",
    "image",
    "menu/food options",
    "in-person",
    "price",
  ],
  study_preregistered: ["yes", "no"],
}
